(cl:in-package piratemainframe-msg)
(cl:export '(START-VAL
          START
          BACK-VAL
          BACK
          TRIG_L-VAL
          TRIG_L
          TRIG_R-VAL
          TRIG_R
          TRIG_L_VAL-VAL
          TRIG_L_VAL
          TRIG_R_VAL-VAL
          TRIG_R_VAL
          BUMP_L-VAL
          BUMP_L
          BUMP_R-VAL
          BUMP_R
          BUT_X-VAL
          BUT_X
          BUT_Y-VAL
          BUT_Y
          BUT_A-VAL
          BUT_A
          BUT_B-VAL
          BUT_B
          AXIS_LX-VAL
          AXIS_LX
          AXIS_LY-VAL
          AXIS_LY
          AXIS_RX-VAL
          AXIS_RX
          AXIS_RY-VAL
          AXIS_RY
          AXIS_DX-VAL
          AXIS_DX
          AXIS_DY-VAL
          AXIS_DY
))